#ifndef _COMPONENTS_DRIVER_AUTOMATIC_H_
#define _COMPONENTS_DRIVER_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Driver_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Driver
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define base_v_VAL components_Driver_CAL_MEM.base_v
#define base_noiselevel_VAL components_Driver_CAL_MEM.base_noiselevel
#define rand_VAL components_Driver_RAM.rand
#define RandomGenerator_instance_VAL components_Driver.RandomGenerator_instance
#define RandomGenerator_instance_REF &(components_Driver.RandomGenerator_instance)
#define RandomGenerator_instance_2_VAL components_Driver.RandomGenerator_instance_2
#define RandomGenerator_instance_2_REF &(components_Driver.RandomGenerator_instance_2)
#define RandomGenerator_instance_3_VAL components_Driver.RandomGenerator_instance_3
#define RandomGenerator_instance_3_REF &(components_Driver.RandomGenerator_instance_3)
#define RandomGenerator_instance_4_VAL components_Driver.RandomGenerator_instance_4
#define RandomGenerator_instance_4_REF &(components_Driver.RandomGenerator_instance_4)
#define deflate_fr_VAL components_Driver_CAL_MEM.deflate_fr
#define deflate_fl_VAL components_Driver_CAL_MEM.deflate_fl
#define deflate_vrl_VAL components_Driver_CAL_MEM.deflate_vrl
#define deflate_vrr_VAL components_Driver_CAL_MEM.deflate_vrr
#define CalcDiviation_instance_VAL components_Driver.CalcDiviation_instance
#define CalcDiviation_instance_REF &(components_Driver.CalcDiviation_instance)
#define CalcDiviation_instance_2_VAL components_Driver.CalcDiviation_instance_2
#define CalcDiviation_instance_2_REF &(components_Driver.CalcDiviation_instance_2)
#define CalcDiviation_instance_3_VAL components_Driver.CalcDiviation_instance_3
#define CalcDiviation_instance_3_REF &(components_Driver.CalcDiviation_instance_3)
#define CalcDiviation_instance_4_VAL components_Driver.CalcDiviation_instance_4
#define CalcDiviation_instance_4_REF &(components_Driver.CalcDiviation_instance_4)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_DRIVER_AUTOMATIC_H_ */
