#ifndef _ASD_COMPONENTS_DRIVER_AUTOMATIC_H_
#define _ASD_COMPONENTS_DRIVER_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Driver_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 18:21:25
*
* @brief   "components_Driver>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_CalcDiviation_Automatic.h"
#include "components_RandomGenerator_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Driver_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_Driver_Automatic_CAL_MEM_SUBSTRUCT {
   float32 base_noiselevel;
   float32 base_v;
   uint8 deflate_fl;
   uint8 deflate_fr;
   uint8 deflate_vrl;
   uint8 deflate_vrr;
   struct components_RandomGenerator_Automatic_CAL_MEM_SUBSTRUCT RandomGenerator_instance;
   struct components_RandomGenerator_Automatic_CAL_MEM_SUBSTRUCT RandomGenerator_instance_2;
   struct components_RandomGenerator_Automatic_CAL_MEM_SUBSTRUCT RandomGenerator_instance_3;
   struct components_RandomGenerator_Automatic_CAL_MEM_SUBSTRUCT RandomGenerator_instance_4;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Driver_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Driver_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_Driver_Automatic_RAM_SUBSTRUCT {
   float32 rand;
   struct components_RandomGenerator_Automatic_RAM_SUBSTRUCT RandomGenerator_instance;
   struct components_RandomGenerator_Automatic_RAM_SUBSTRUCT RandomGenerator_instance_2;
   struct components_RandomGenerator_Automatic_RAM_SUBSTRUCT RandomGenerator_instance_3;
   struct components_RandomGenerator_Automatic_RAM_SUBSTRUCT RandomGenerator_instance_4;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Driver_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_Driver_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_Driver_Automatic {
   struct components_RandomGenerator_Automatic RandomGenerator_instance;
   struct components_RandomGenerator_Automatic RandomGenerator_instance_2;
   struct components_RandomGenerator_Automatic RandomGenerator_instance_3;
   struct components_RandomGenerator_Automatic RandomGenerator_instance_4;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_Driver_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ................components_Driver_Automatic */
#define _components_Driver_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_Driver_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct components_Driver_Automatic_CAL_MEM_SUBSTRUCT components_Driver_CAL_MEM;

/* forward declaration of substruct variable 'components_Driver_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_Driver_Automatic_RAM_SUBSTRUCT components_Driver_RAM;

/* forward declaration of component variable 'components_Driver' */
/* containing 'ROM' memory class tree */
extern const struct components_Driver_Automatic components_Driver;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_Driver_Automatic
 ******************************************************************************/
extern void components_Driver_Automatic_calc (void);



#endif /* _ASD_COMPONENTS_DRIVER_AUTOMATIC_H_ */
