#ifndef _COMPONENTS_SIMULATION_AUTOMATIC_H_
#define _COMPONENTS_SIMULATION_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Simulation_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Simulation
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define sfl_VAL components_Simulation_RAM.sfl
#define srl_VAL components_Simulation_RAM.srl
#define srr_VAL components_Simulation_RAM.srr
#define sfr_VAL components_Simulation_RAM.sfr
#define rand_VAL components_Simulation_RAM.rand
#define status_tire_VAL components_Simulation_CAL_MEM.status_tire
#define diff_sfl_VAL components_Simulation_RAM.diff_sfl
#define diff_sfr_VAL components_Simulation_RAM.diff_sfr
#define diff_srr_VAL components_Simulation_RAM.diff_srr
#define diff_srl_VAL components_Simulation_RAM.diff_srl
#define Model_instance_VAL components_Simulation.Model_instance
#define Model_instance_REF &(components_Simulation.Model_instance)
#define TireMean_instance_VAL components_Simulation.TireMean_instance
#define TireMean_instance_REF &(components_Simulation.TireMean_instance)
#define mean_VAL components_Simulation_RAM.mean
#define TireDeviation_instance_VAL components_Simulation.TireDeviation_instance
#define TireDeviation_instance_REF &(components_Simulation.TireDeviation_instance)
#define fl_failure_VAL components_Simulation_RAM.fl_failure
#define fr_failure_VAL components_Simulation_RAM.fr_failure
#define rl_failure_VAL components_Simulation_RAM.rl_failure
#define rr_failure_VAL components_Simulation_RAM.rr_failure
#define RandomGenerator_instance_VAL components_Simulation.RandomGenerator_instance
#define RandomGenerator_instance_REF &(components_Simulation.RandomGenerator_instance)
#define base_v_VAL components_Simulation_CAL_MEM.base_v
#define base_noiselevel_VAL components_Simulation_CAL_MEM.base_noiselevel
#define vfr_VAL components_Simulation_RAM.vfr
#define vrr_VAL components_Simulation_RAM.vrr
#define vfl_VAL components_Simulation_RAM.vfl
#define vrl_VAL components_Simulation_RAM.vrl
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_SIMULATION_AUTOMATIC_H_ */
