/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Driver_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 18:21:25
*
* @brief   "components_Driver>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Driver_Automatic.h"
#include "interfaces_interfaces_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Driver_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'components_Driver'
 * data set:.....................................'COMPONENTS_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Driver_Automatic_CAL_MEM_SUBSTRUCT components_Driver_CAL_MEM = {
   /* struct element:'components_Driver_CAL_MEM.base_noiselevel' (modeled as:'base_noiselevel.components_Driver') */
   0.0F,
   /* struct element:'components_Driver_CAL_MEM.base_v' (modeled as:'base_v.components_Driver') */
   0.0F,
   /* struct element:'components_Driver_CAL_MEM.deflate_fl' (modeled as:'deflate_fl.components_Driver') */
   false,
   /* struct element:'components_Driver_CAL_MEM.deflate_fr' (modeled as:'deflate_fr.components_Driver') */
   false,
   /* struct element:'components_Driver_CAL_MEM.deflate_vrl' (modeled as:'deflate_vrl.components_Driver') */
   false,
   /* struct element:'components_Driver_CAL_MEM.deflate_vrr' (modeled as:'deflate_vrr.components_Driver') */
   false,
   /* substruct: components_Driver_CAL_MEM.RandomGenerator_instance (modeled as:'RandomGenerator_instance.components_Driver') */
   {
      /* struct element:'components_Driver_CAL_MEM.RandomGenerator_instance.a' (modeled as:'a.RandomGenerator_instance.components_Driver') */
      89U,
      /* struct element:'components_Driver_CAL_MEM.RandomGenerator_instance.c' (modeled as:'c.RandomGenerator_instance.components_Driver') */
      251U,
      /* struct element:'components_Driver_CAL_MEM.RandomGenerator_instance.m' (modeled as:'m.RandomGenerator_instance.components_Driver') */
      1024U
   },
   /* substruct: components_Driver_CAL_MEM.RandomGenerator_instance_2 (modeled as:'RandomGenerator_instance_2.components_Driver') */
   {
      /* struct element:'components_Driver_CAL_MEM.RandomGenerator_instance_2.a' (modeled as:'a.RandomGenerator_instance_2.components_Driver') */
      89U,
      /* struct element:'components_Driver_CAL_MEM.RandomGenerator_instance_2.c' (modeled as:'c.RandomGenerator_instance_2.components_Driver') */
      251U,
      /* struct element:'components_Driver_CAL_MEM.RandomGenerator_instance_2.m' (modeled as:'m.RandomGenerator_instance_2.components_Driver') */
      1024U
   },
   /* substruct: components_Driver_CAL_MEM.RandomGenerator_instance_3 (modeled as:'RandomGenerator_instance_3.components_Driver') */
   {
      /* struct element:'components_Driver_CAL_MEM.RandomGenerator_instance_3.a' (modeled as:'a.RandomGenerator_instance_3.components_Driver') */
      89U,
      /* struct element:'components_Driver_CAL_MEM.RandomGenerator_instance_3.c' (modeled as:'c.RandomGenerator_instance_3.components_Driver') */
      251U,
      /* struct element:'components_Driver_CAL_MEM.RandomGenerator_instance_3.m' (modeled as:'m.RandomGenerator_instance_3.components_Driver') */
      1024U
   },
   /* substruct: components_Driver_CAL_MEM.RandomGenerator_instance_4 (modeled as:'RandomGenerator_instance_4.components_Driver') */
   {
      /* struct element:'components_Driver_CAL_MEM.RandomGenerator_instance_4.a' (modeled as:'a.RandomGenerator_instance_4.components_Driver') */
      89U,
      /* struct element:'components_Driver_CAL_MEM.RandomGenerator_instance_4.c' (modeled as:'c.RandomGenerator_instance_4.components_Driver') */
      251U,
      /* struct element:'components_Driver_CAL_MEM.RandomGenerator_instance_4.m' (modeled as:'m.RandomGenerator_instance_4.components_Driver') */
      1024U
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Driver_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Driver_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_Driver'
 * data set:.....................................'COMPONENTS_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Driver_Automatic_RAM_SUBSTRUCT components_Driver_RAM = {
   /* struct element:'components_Driver_RAM.rand' (modeled as:'rand.components_Driver') */
   0.0F,
   /* substruct: components_Driver_RAM.RandomGenerator_instance (modeled as:'RandomGenerator_instance.components_Driver') */
   {
      /* struct element:'components_Driver_RAM.RandomGenerator_instance.seed' (modeled as:'seed.RandomGenerator_instance.components_Driver') */
      0U,
      /* struct element:'components_Driver_RAM.RandomGenerator_instance.x' (modeled as:'x.RandomGenerator_instance.components_Driver') */
      0U
   },
   /* substruct: components_Driver_RAM.RandomGenerator_instance_2 (modeled as:'RandomGenerator_instance_2.components_Driver') */
   {
      /* struct element:'components_Driver_RAM.RandomGenerator_instance_2.seed' (modeled as:'seed.RandomGenerator_instance_2.components_Driver') */
      0U,
      /* struct element:'components_Driver_RAM.RandomGenerator_instance_2.x' (modeled as:'x.RandomGenerator_instance_2.components_Driver') */
      0U
   },
   /* substruct: components_Driver_RAM.RandomGenerator_instance_3 (modeled as:'RandomGenerator_instance_3.components_Driver') */
   {
      /* struct element:'components_Driver_RAM.RandomGenerator_instance_3.seed' (modeled as:'seed.RandomGenerator_instance_3.components_Driver') */
      0U,
      /* struct element:'components_Driver_RAM.RandomGenerator_instance_3.x' (modeled as:'x.RandomGenerator_instance_3.components_Driver') */
      0U
   },
   /* substruct: components_Driver_RAM.RandomGenerator_instance_4 (modeled as:'RandomGenerator_instance_4.components_Driver') */
   {
      /* struct element:'components_Driver_RAM.RandomGenerator_instance_4.seed' (modeled as:'seed.RandomGenerator_instance_4.components_Driver') */
      0U,
      /* struct element:'components_Driver_RAM.RandomGenerator_instance_4.x' (modeled as:'x.RandomGenerator_instance_4.components_Driver') */
      0U
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Driver_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_Driver'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_Driver'
 * data set:.....................................'COMPONENTS_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_Driver_Automatic components_Driver = {
   /* substruct: components_Driver.RandomGenerator_instance (modeled as:'RandomGenerator_instance.components_Driver') */
   {
      /* type descriptor pointer 'components_RandomGenerator_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Driver_CAL_MEM.RandomGenerator_instance,
      /* type descriptor pointer 'components_RandomGenerator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Driver_RAM.RandomGenerator_instance
   },
   /* substruct: components_Driver.RandomGenerator_instance_2 (modeled as:'RandomGenerator_instance_2.components_Driver') */
   {
      /* type descriptor pointer 'components_RandomGenerator_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Driver_CAL_MEM.RandomGenerator_instance_2,
      /* type descriptor pointer 'components_RandomGenerator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Driver_RAM.RandomGenerator_instance_2
   },
   /* substruct: components_Driver.RandomGenerator_instance_3 (modeled as:'RandomGenerator_instance_3.components_Driver') */
   {
      /* type descriptor pointer 'components_RandomGenerator_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Driver_CAL_MEM.RandomGenerator_instance_3,
      /* type descriptor pointer 'components_RandomGenerator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Driver_RAM.RandomGenerator_instance_3
   },
   /* substruct: components_Driver.RandomGenerator_instance_4 (modeled as:'RandomGenerator_instance_4.components_Driver') */
   {
      /* type descriptor pointer 'components_RandomGenerator_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Driver_CAL_MEM.RandomGenerator_instance_4,
      /* type descriptor pointer 'components_RandomGenerator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Driver_RAM.RandomGenerator_instance_4
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_Driver'
 ******************************************************************************/





#define base_noiselevel_VAL (components_Driver_CAL_MEM.base_noiselevel)
#define base_v_VAL (components_Driver_CAL_MEM.base_v)
#define deflate_fl_VAL (components_Driver_CAL_MEM.deflate_fl)
#define deflate_fr_VAL (components_Driver_CAL_MEM.deflate_fr)
#define deflate_vrl_VAL (components_Driver_CAL_MEM.deflate_vrl)
#define deflate_vrr_VAL (components_Driver_CAL_MEM.deflate_vrr)
#define RandomGenerator_instance_2_REF (&(components_Driver.RandomGenerator_instance_2))
#define RandomGenerator_instance_3_REF (&(components_Driver.RandomGenerator_instance_3))
#define RandomGenerator_instance_4_REF (&(components_Driver.RandomGenerator_instance_4))
#define RandomGenerator_instance_REF (&(components_Driver.RandomGenerator_instance))


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'components_Driver_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */


void components_Driver_Automatic_calc (void)
{
   /* define local message copies */
   float32 interfaces_interfaces_vfl__components_Driver_Automatic_calc;
   float32 interfaces_interfaces_vfr__components_Driver_Automatic_calc;
   float32 interfaces_interfaces_vrl__components_Driver_Automatic_calc;
   float32 interfaces_interfaces_vrr__components_Driver_Automatic_calc;
   /* receive messages implicitly */
   {
      DisableAllInterrupts();
      interfaces_interfaces_vfl__components_Driver_Automatic_calc = interfaces_interfaces_vfl;
      interfaces_interfaces_vfr__components_Driver_Automatic_calc = interfaces_interfaces_vfr;
      interfaces_interfaces_vrl__components_Driver_Automatic_calc = interfaces_interfaces_vrl;
      interfaces_interfaces_vrr__components_Driver_Automatic_calc = interfaces_interfaces_vrr;
      EnableAllInterrupts();
   }
   interfaces_interfaces_vfr__components_Driver_Automatic_calc
      = components_CalcDiviation_Automatic_calc(deflate_fr_VAL, components_RandomGenerator_Automatic_calc(RandomGenerator_instance_REF, base_v_VAL, base_noiselevel_VAL, 123));
   interfaces_interfaces_vfl__components_Driver_Automatic_calc
      = components_CalcDiviation_Automatic_calc(deflate_fl_VAL, components_RandomGenerator_Automatic_calc(RandomGenerator_instance_2_REF, base_v_VAL, base_noiselevel_VAL, 456));
   interfaces_interfaces_vrl__components_Driver_Automatic_calc
      = components_CalcDiviation_Automatic_calc(deflate_vrl_VAL, components_RandomGenerator_Automatic_calc(RandomGenerator_instance_3_REF, base_v_VAL, base_noiselevel_VAL, 789));
   interfaces_interfaces_vrr__components_Driver_Automatic_calc
      = components_CalcDiviation_Automatic_calc(deflate_vrr_VAL, components_RandomGenerator_Automatic_calc(RandomGenerator_instance_4_REF, base_v_VAL, base_noiselevel_VAL, 901));
   /* send messages implicitly */
   {
      DisableAllInterrupts();
      interfaces_interfaces_vfl = interfaces_interfaces_vfl__components_Driver_Automatic_calc;
      interfaces_interfaces_vfr = interfaces_interfaces_vfr__components_Driver_Automatic_calc;
      interfaces_interfaces_vrl = interfaces_interfaces_vrl__components_Driver_Automatic_calc;
      interfaces_interfaces_vrr = interfaces_interfaces_vrr__components_Driver_Automatic_calc;
      EnableAllInterrupts();
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'components_Driver_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



