#ifndef _ASD_COMPONENTS_TIREDEVIATION_AUTOMATIC_H_
#define _ASD_COMPONENTS_TIREDEVIATION_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_TireDeviation_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:25:43
*
* @brief   "components_TireDeviation>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_TireDeviation_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_TireDeviation_Automatic_RAM_SUBSTRUCT {
   float32 diff;
   float32 limit;
   float32 mean;
   float32 v;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_TireDeviation_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_TireDeviation_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_TireDeviation_Automatic {
   struct components_TireDeviation_Automatic_RAM_SUBSTRUCT * components_TireDeviation_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_TireDeviation_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .........components_TireDeviation_Automatic */
#define _components_TireDeviation_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_TireDeviation_Automatic
 ******************************************************************************/
extern uint8 components_TireDeviation_Automatic_calc (
               const struct components_TireDeviation_Automatic * self,
   /* IN    */ const float32                                     v_single,
   /* IN    */ const float32                                     v_mean,
   /* IN    */ const float32                                     esdl_calc_limit,
   /* IN    */ const uint8                                       noFailure
   );



#endif /* _ASD_COMPONENTS_TIREDEVIATION_AUTOMATIC_H_ */
