#ifndef _ASD_COMPONENTS_CALCDIVIATION_AUTOMATIC_H_
#define _ASD_COMPONENTS_CALCDIVIATION_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_CalcDiviation_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 18:21:25
*
* @brief   "components_CalcDiviation>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for class COMPONENTS_CALCDIVIATION_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .........components_CalcDiviation_Automatic */
#define _components_CalcDiviation_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_CalcDiviation_Automatic
 ******************************************************************************/
extern float32 components_CalcDiviation_Automatic_calc (
   /* IN    */ const uint8   deflate,
   /* IN    */ const float32 v
   );



#endif /* _ASD_COMPONENTS_CALCDIVIATION_AUTOMATIC_H_ */
