/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_CalcDiviation_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 18:21:25
*
* @brief   "components_CalcDiviation>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_CalcDiviation_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/





/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_CalcDiviation_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_CalcDiviation_Automatic_calc (
   /* IN    */ const uint8   deflate,
   /* IN    */ const float32 v
   )
{
   if (deflate)
   {
      return v * 0.994F;
   }
   else
   {
      return v;
   } /* end if */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_CalcDiviation_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



