#ifndef _ASD_COMPONENTS_SIM_STATEMACHINE_AUTOMATIC_H_
#define _ASD_COMPONENTS_SIM_STATEMACHINE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_sim_statemachine_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 18:21:25
*
* @brief   "components_sim_statemachine>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_SOS_state_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_sim_statemachine_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_sim_statemachine_Automatic_CAL_MEM_SUBSTRUCT {
   uint8 failure;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_sim_statemachine_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_sim_statemachine_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_sim_statemachine_Automatic_RAM_SUBSTRUCT {
   struct components_SOS_state_Automatic_RAM_SUBSTRUCT SOS_state_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_sim_statemachine_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_sim_statemachine_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_sim_statemachine_Automatic {
   struct components_SOS_state_Automatic SOS_state_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_sim_statemachine_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ......components_sim_statemachine_Automatic */
#define _components_sim_statemachine_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_sim_statemachine_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct components_sim_statemachine_Automatic_CAL_MEM_SUBSTRUCT components_sim_statemachine_CAL_MEM;

/* forward declaration of substruct variable 'components_sim_statemachine_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_sim_statemachine_Automatic_RAM_SUBSTRUCT components_sim_statemachine_RAM;

/* forward declaration of component variable 'components_sim_statemachine' */
/* containing 'ROM' memory class tree */
extern const struct components_sim_statemachine_Automatic components_sim_statemachine;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_sim_statemachine_Automatic
 ******************************************************************************/
extern void components_sim_statemachine_Automatic_calc (void);



#endif /* _ASD_COMPONENTS_SIM_STATEMACHINE_AUTOMATIC_H_ */
