/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_RandomGenerator_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:25:43
*
* @brief   "components_RandomGenerator>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_RandomGenerator_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define a_VAL (self->components_RandomGenerator_Automatic_CAL_MEM->a)
#define c_VAL (self->components_RandomGenerator_Automatic_CAL_MEM->c)
#define m_VAL (self->components_RandomGenerator_Automatic_CAL_MEM->m)
#define x_VAL (self->components_RandomGenerator_Automatic_RAM->x)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_RandomGenerator_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_RandomGenerator_Automatic_calc (
               const struct components_RandomGenerator_Automatic * self,
   /* IN    */ const float32                                       set_vel,
   /* IN    */ const float32                                       noiselevel,
   /* IN    */ const sint32                                        mySeed
   )
{
   /* temp. variables */
   sint32 _t1sint32;
   uint32 _t1uint32;
   float32 _t1real32;

   if ((sint32)x_VAL == 0)
   {
      _t1sint32 = ((mySeed >= 0) ? (((mySeed <= 1024) ? mySeed : 1024)) : 0);
      x_VAL = (uint16)_t1sint32;
   } /* end if */
   _t1uint32 = ((uint32)x_VAL * a_VAL) + c_VAL;
   x_VAL
      = (uint16)(((m_VAL == 0U) ? (((_t1uint32 <= 1023U) ? _t1uint32 : 1023U)) : (_t1uint32 % m_VAL)));
   _t1real32
      = noiselevel * ((float32)x_VAL - ((float32)m_VAL * 0.5F)) * 2.0F;
   return set_vel + ((((float32)m_VAL == 0.0F) ? _t1real32 : (_t1real32 / (float32)m_VAL)));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_RandomGenerator_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



