#ifndef _ASD_COMPONENTS_TIREMEAN_AUTOMATIC_H_
#define _ASD_COMPONENTS_TIREMEAN_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_TireMean_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:25:43
*
* @brief   "components_TireMean>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for class COMPONENTS_TIREMEAN_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..............components_TireMean_Automatic */
#define _components_TireMean_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_TireMean_Automatic
 ******************************************************************************/
extern float32 components_TireMean_Automatic_calc (
   /* IN    */ const float32 v1,
   /* IN    */ const float32 v3,
   /* IN    */ const float32 v2,
   /* IN    */ const float32 v4
   );



#endif /* _ASD_COMPONENTS_TIREMEAN_AUTOMATIC_H_ */
