#ifndef _COMPONENTS_RINGBUFFER_AUTOMATIC_H_
#define _COMPONENTS_RINGBUFFER_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_RingBuffer_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_RingBuffer
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define buffer_VAL self->components_RingBuffer_Automatic_RAM->buffer
#define buffer_REF self->components_RingBuffer_Automatic_RAM->buffer
#define c_VAL self->components_RingBuffer_Automatic_RAM->c
#define swap_VAL self->components_RingBuffer_Automatic_RAM->swap
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_RINGBUFFER_AUTOMATIC_H_ */
