#ifndef _COMPONENTS_SIM_STATEMACHINE_AUTOMATIC_H_
#define _COMPONENTS_SIM_STATEMACHINE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_sim_statemachine_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_sim_statemachine
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define SOS_state_instance_VAL components_sim_statemachine.SOS_state_instance
#define SOS_state_instance_REF &(components_sim_statemachine.SOS_state_instance)
#define failure_VAL components_sim_statemachine_CAL_MEM.failure
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_SIM_STATEMACHINE_AUTOMATIC_H_ */
