#ifndef _ASD_INTERFACES_INTERFACES_AUTOMATIC_H_
#define _ASD_INTERFACES_INTERFACES_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    interfaces_interfaces_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 18:21:25
*
* @brief   "interfaces_interfaces>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module INTERFACES_INTERFACES_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ............interfaces_interfaces_Automatic */
#define _interfaces_interfaces_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module interfaces_interfaces_Automatic
 ******************************************************************************/


/* declaration of messages */
extern float32 interfaces_interfaces_delta_sfl;
extern float32 interfaces_interfaces_delta_sfr;
extern float32 interfaces_interfaces_delta_srl;
extern float32 interfaces_interfaces_delta_srr;
extern uint8 interfaces_interfaces_failure_detected;
extern float32 interfaces_interfaces_mean;
extern float32 interfaces_interfaces_vfl;
extern float32 interfaces_interfaces_vfr;
extern float32 interfaces_interfaces_vrl;
extern float32 interfaces_interfaces_vrr;


#endif /* _ASD_INTERFACES_INTERFACES_AUTOMATIC_H_ */
