/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    interfaces_interfaces_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:25:43
*
* @brief   "interfaces_interfaces>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "interfaces_interfaces_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'interfaces_interfaces'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/






/******************************************************************************
 * BEGIN: DEFINITION OF MESSAGES
 * ----------------------------------------------------------------------------
 * Total size is [bytes]:........................54
 * ---------------------------------------------------------------------------*/
/* messages of memory class:............................................'RAM' */
/* messages of size [bytes]:................................................4 */
/* modelled as 'interfaces_interfaces_delta_sfl' */
float32 interfaces_interfaces_delta_sfl = 0.0F;
/* modelled as 'interfaces_interfaces_delta_sfr' */
float32 interfaces_interfaces_delta_sfr = 0.0F;
/* modelled as 'interfaces_interfaces_delta_srl' */
float32 interfaces_interfaces_delta_srl = 0.0F;
/* modelled as 'interfaces_interfaces_delta_srr' */
float32 interfaces_interfaces_delta_srr = 0.0F;
/* modelled as 'interfaces_interfaces_mean' */
float32 interfaces_interfaces_mean = 0.0F;
/* modelled as 'interfaces_interfaces_sfl' */
float32 interfaces_interfaces_sfl = 0.0F;
/* modelled as 'interfaces_interfaces_sfr' */
float32 interfaces_interfaces_sfr = 0.0F;
/* modelled as 'interfaces_interfaces_srl' */
float32 interfaces_interfaces_srl = 0.0F;
/* modelled as 'interfaces_interfaces_srr' */
float32 interfaces_interfaces_srr = 0.0F;
/* modelled as 'interfaces_interfaces_vfl' */
float32 interfaces_interfaces_vfl = 0.0F;
/* modelled as 'interfaces_interfaces_vfr' */
float32 interfaces_interfaces_vfr = 0.0F;
/* modelled as 'interfaces_interfaces_vrl' */
float32 interfaces_interfaces_vrl = 0.0F;
/* modelled as 'interfaces_interfaces_vrr' */
float32 interfaces_interfaces_vrr = 0.0F;
/* messages of size [bytes]:................................................1 */
/* modelled as 'interfaces_interfaces_failure_detected' */
uint8 interfaces_interfaces_failure_detected = false;
/* modelled as 'interfaces_interfaces_noFailure' */
uint8 interfaces_interfaces_noFailure = false;
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MESSAGES
 ******************************************************************************/



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



