#ifndef _RUNNABLEMODELS_TIREPRESSUREMONITORING_AUTOMATIC_H_
#define _RUNNABLEMODELS_TIREPRESSUREMONITORING_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    runnableModels_TirePressureMonitoring_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component runnableModels_TirePressureMonitoring
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define fr_failure_VAL runnableModels_TirePressureMonitoring_RAM.fr_failure
#define diff_sfr_VAL runnableModels_TirePressureMonitoring_RAM.diff_sfr
#define diff_sfl_VAL runnableModels_TirePressureMonitoring_RAM.diff_sfl
#define diff_srl_VAL runnableModels_TirePressureMonitoring_RAM.diff_srl
#define rr_failure_VAL runnableModels_TirePressureMonitoring_RAM.rr_failure
#define rl_failure_VAL runnableModels_TirePressureMonitoring_RAM.rl_failure
#define diff_srr_VAL runnableModels_TirePressureMonitoring_RAM.diff_srr
#define fl_failure_VAL runnableModels_TirePressureMonitoring_RAM.fl_failure
#define TireMean_instance_VAL runnableModels_TirePressureMonitoring.TireMean_instance
#define TireMean_instance_REF &(runnableModels_TirePressureMonitoring.TireMean_instance)
#define mean_VAL runnableModels_TirePressureMonitoring_RAM.mean
#define test_VAL runnableModels_TirePressureMonitoring_RAM.test
#define TireDeviation_instance_VAL runnableModels_TirePressureMonitoring.TireDeviation_instance
#define TireDeviation_instance_REF &(runnableModels_TirePressureMonitoring.TireDeviation_instance)
#define TireDeviation_instance_2_VAL runnableModels_TirePressureMonitoring.TireDeviation_instance_2
#define TireDeviation_instance_2_REF &(runnableModels_TirePressureMonitoring.TireDeviation_instance_2)
#define TireDeviation_instance_3_VAL runnableModels_TirePressureMonitoring.TireDeviation_instance_3
#define TireDeviation_instance_3_REF &(runnableModels_TirePressureMonitoring.TireDeviation_instance_3)
#define TireDeviation_instance_4_VAL runnableModels_TirePressureMonitoring.TireDeviation_instance_4
#define TireDeviation_instance_4_REF &(runnableModels_TirePressureMonitoring.TireDeviation_instance_4)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _RUNNABLEMODELS_TIREPRESSUREMONITORING_AUTOMATIC_H_ */
