#ifndef _ASD_RUNNABLEMODELS_RESETFUNCTIONALITY_AUTOMATIC_H_
#define _ASD_RUNNABLEMODELS_RESETFUNCTIONALITY_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    runnableModels_ResetFunctionality_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:25:43
*
* @brief   "runnableModels_ResetFunctionality>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_Reset_Automatic.h"
#include "runnableModels_ResetStateMachine_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'runnableModels_ResetFunctionality_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct runnableModels_ResetFunctionality_Automatic_CAL_MEM_SUBSTRUCT {
   uint8 ResetButton;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'runnableModels_ResetFunctionality_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'runnableModels_ResetFunctionality_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct runnableModels_ResetFunctionality_Automatic_RAM_SUBSTRUCT {
   uint8 exitState;
   uint8 restValid;
   uint8 test;
   struct runnableModels_ResetStateMachine_Automatic_RAM_SUBSTRUCT ResetStateMachine_instance;
   struct runnableModels_ResetStateMachine_Automatic_RAM_SUBSTRUCT ResetStateMachine_instance_2;
   struct runnableModels_ResetStateMachine_Automatic_RAM_SUBSTRUCT ResetStateMachine_instance_3;
   struct runnableModels_ResetStateMachine_Automatic_RAM_SUBSTRUCT ResetStateMachine_instance_4;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'runnableModels_ResetFunctionality_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'runnableModels_ResetFunctionality_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct runnableModels_ResetFunctionality_Automatic {
   struct runnableModels_ResetStateMachine_Automatic ResetStateMachine_instance;
   struct runnableModels_ResetStateMachine_Automatic ResetStateMachine_instance_2;
   struct runnableModels_ResetStateMachine_Automatic ResetStateMachine_instance_3;
   struct runnableModels_ResetStateMachine_Automatic ResetStateMachine_instance_4;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'runnableModels_ResetFunctionality_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: runnableModels_ResetFunctionality_Automatic */
#define _runnableModels_ResetFunctionality_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'runnableModels_ResetFunctionality_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct runnableModels_ResetFunctionality_Automatic_CAL_MEM_SUBSTRUCT runnableModels_ResetFunctionality_CAL_MEM;

/* forward declaration of substruct variable 'runnableModels_ResetFunctionality_RAM' */
/* containing 'RAM' memory class tree */
extern struct runnableModels_ResetFunctionality_Automatic_RAM_SUBSTRUCT runnableModels_ResetFunctionality_RAM;

/* forward declaration of component variable 'runnableModels_ResetFunctionality' */
/* containing 'ROM' memory class tree */
extern const struct runnableModels_ResetFunctionality_Automatic runnableModels_ResetFunctionality;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module runnableModels_ResetFunctionality_Automatic
 ******************************************************************************/
extern void runnableModels_ResetFunctionality_Automatic_calc (void);



#endif /* _ASD_RUNNABLEMODELS_RESETFUNCTIONALITY_AUTOMATIC_H_ */
