#ifndef _RUNNABLEMODELS_RESETSTATEMACHINE_AUTOMATIC_H_
#define _RUNNABLEMODELS_RESETSTATEMACHINE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    runnableModels_ResetStateMachine_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component runnableModels_ResetStateMachine
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define reset_VAL self->runnableModels_ResetStateMachine_Automatic_RAM->reset
#define myDT_VAL self->runnableModels_ResetStateMachine_Automatic_RAM->myDT
#define delta_xx_VAL self->runnableModels_ResetStateMachine_Automatic_RAM->delta_xx
#define mean_VAL self->runnableModels_ResetStateMachine_Automatic_RAM->mean
#define new_limit_VAL self->runnableModels_ResetStateMachine_Automatic_RAM->new_limit
#define duration_VAL self->runnableModels_ResetStateMachine_Automatic_RAM->duration
#define diff_xx_VAL self->runnableModels_ResetStateMachine_Automatic_RAM->diff_xx
#define limit_VAL self->runnableModels_ResetStateMachine_Automatic_RAM->limit
#define setDone_VAL self->runnableModels_ResetStateMachine_Automatic_RAM->setDone
#define noFailure_VAL self->runnableModels_ResetStateMachine_Automatic_RAM->noFailure
#define sm_VAL self->runnableModels_ResetStateMachine_Automatic_RAM->sm
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _RUNNABLEMODELS_RESETSTATEMACHINE_AUTOMATIC_H_ */
