#ifndef _ASD_RUNNABLEMODELS_SIMULATION_AUTOMATIC_H_
#define _ASD_RUNNABLEMODELS_SIMULATION_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    runnableModels_Simulation_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:25:43
*
* @brief   "runnableModels_Simulation>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_Model_Automatic.h"
#include "components_RandomGenerator_Automatic.h"
#include "components_TireDeviation_Automatic.h"
#include "components_TireMean_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'runnableModels_Simulation_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct runnableModels_Simulation_Automatic_CAL_MEM_SUBSTRUCT {
   float32 base_noiselevel;
   float32 base_v;
   uint8 status_tire;
   struct components_RandomGenerator_Automatic_CAL_MEM_SUBSTRUCT RandomGenerator_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'runnableModels_Simulation_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'runnableModels_Simulation_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct runnableModels_Simulation_Automatic_RAM_SUBSTRUCT {
   float32 diff_sfl;
   float32 diff_sfr;
   float32 diff_srl;
   float32 diff_srr;
   float32 mean;
   float32 rand;
   float32 sfl;
   float32 sfr;
   float32 srl;
   float32 srr;
   float32 vfl;
   float32 vfr;
   float32 vrl;
   float32 vrr;
   uint8 fl_failure;
   uint8 fr_failure;
   uint8 rl_failure;
   uint8 rr_failure;
   struct components_Model_Automatic_RAM_SUBSTRUCT Model_instance;
   struct components_RandomGenerator_Automatic_RAM_SUBSTRUCT RandomGenerator_instance;
   struct components_TireDeviation_Automatic_RAM_SUBSTRUCT TireDeviation_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'runnableModels_Simulation_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'runnableModels_Simulation_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct runnableModels_Simulation_Automatic {
   struct components_Model_Automatic Model_instance;
   struct components_RandomGenerator_Automatic RandomGenerator_instance;
   struct components_TireDeviation_Automatic TireDeviation_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'runnableModels_Simulation_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ........runnableModels_Simulation_Automatic */
#define _runnableModels_Simulation_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'runnableModels_Simulation_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct runnableModels_Simulation_Automatic_CAL_MEM_SUBSTRUCT runnableModels_Simulation_CAL_MEM;

/* forward declaration of substruct variable 'runnableModels_Simulation_RAM' */
/* containing 'RAM' memory class tree */
extern struct runnableModels_Simulation_Automatic_RAM_SUBSTRUCT runnableModels_Simulation_RAM;

/* forward declaration of component variable 'runnableModels_Simulation' */
/* containing 'ROM' memory class tree */
extern const struct runnableModels_Simulation_Automatic runnableModels_Simulation;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module runnableModels_Simulation_Automatic
 ******************************************************************************/
extern void runnableModels_Simulation_Automatic_calc (void);



#endif /* _ASD_RUNNABLEMODELS_SIMULATION_AUTOMATIC_H_ */
