/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    runnableModels_ResetStateMachine_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:25:43
*
* @brief   "runnableModels_ResetStateMachine>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "runnableModels_ResetStateMachine_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define delta_xx_VAL (self->runnableModels_ResetStateMachine_Automatic_RAM->delta_xx)
#define diff_xx_VAL (self->runnableModels_ResetStateMachine_Automatic_RAM->diff_xx)
#define duration_VAL (self->runnableModels_ResetStateMachine_Automatic_RAM->duration)
#define limit_VAL (self->runnableModels_ResetStateMachine_Automatic_RAM->limit)
#define mean_VAL (self->runnableModels_ResetStateMachine_Automatic_RAM->mean)
#define myDT_VAL (self->runnableModels_ResetStateMachine_Automatic_RAM->myDT)
#define new_limit_VAL (self->runnableModels_ResetStateMachine_Automatic_RAM->new_limit)
#define noFailure_VAL (self->runnableModels_ResetStateMachine_Automatic_RAM->noFailure)
#define reset_VAL (self->runnableModels_ResetStateMachine_Automatic_RAM->reset)
#define setDone_VAL (self->runnableModels_ResetStateMachine_Automatic_RAM->setDone)
#define sm_VAL (self->runnableModels_ResetStateMachine_Automatic_RAM->sm)

/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define DoNothing 0U
#define Reset 1U
#define WaitForGo 2U
#define WaitForReset 3U



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'runnableModels_ResetStateMachine_Automatic_esdl_getState'
 * ----------------------------------------------------------------------------
 * model name:...................................'esdl_getState'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

uint8 runnableModels_ResetStateMachine_Automatic_esdl_getState ( const struct runnableModels_ResetStateMachine_Automatic * self)
{
   return sm_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'runnableModels_ResetStateMachine_Automatic_esdl_getState'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'runnableModels_ResetStateMachine_Automatic_resetStateMachineStatemachineTrigger'
 * ----------------------------------------------------------------------------
 * model name:...................................'resetStateMachineStatemachineTrigger'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void runnableModels_ResetStateMachine_Automatic_resetStateMachineStatemachineTrigger ( const struct runnableModels_ResetStateMachine_Automatic * self)
{
   /* temp. variables */
   float32 _t1real32;

   switch (sm_VAL)
   {
      case Reset:
         if (setDone_VAL)
         {
            setDone_VAL = false;
            noFailure_VAL = false;
            sm_VAL = DoNothing;
            break;
         } /* end if */
         break;
      case WaitForGo:
         if (!reset_VAL)
         {
            reset_VAL = false;
            duration_VAL = 0.0F;
            sm_VAL = WaitForReset;
            break;
         } /* end if */
         break;
      case WaitForReset:
         if (duration_VAL > 20.0F)
         {
            limit_VAL = 0.5F;
            _t1real32 = mean_VAL - delta_xx_VAL;
            _t1real32 = ((_t1real32 > 0.0F) ? _t1real32 : -_t1real32);
            diff_xx_VAL = ((mean_VAL == 0.0F) ? _t1real32 : (_t1real32 / mean_VAL));
            new_limit_VAL = limit_VAL + (diff_xx_VAL * 100.0F);
            setDone_VAL = true;
            sm_VAL = Reset;
            break;
         } /* end if */
         duration_VAL = duration_VAL + myDT_VAL;
         break;
      case DoNothing:
      default:
         if (reset_VAL)
         {
            noFailure_VAL = true;
            sm_VAL = WaitForGo;
            break;
         } /* end if */
         break;
   } /* end switch */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'runnableModels_ResetStateMachine_Automatic_resetStateMachineStatemachineTrigger'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



