#ifndef _RUNNABLEMODELS_DRIVER_AUTOMATIC_H_
#define _RUNNABLEMODELS_DRIVER_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    runnableModels_Driver_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component runnableModels_Driver
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define base_v_VAL runnableModels_Driver_CAL_MEM.base_v
#define base_noiselevel_VAL runnableModels_Driver_CAL_MEM.base_noiselevel
#define rand_VAL runnableModels_Driver_RAM.rand
#define RandomGenerator_instance_VAL runnableModels_Driver.RandomGenerator_instance
#define RandomGenerator_instance_REF &(runnableModels_Driver.RandomGenerator_instance)
#define RandomGenerator_instance_2_VAL runnableModels_Driver.RandomGenerator_instance_2
#define RandomGenerator_instance_2_REF &(runnableModels_Driver.RandomGenerator_instance_2)
#define RandomGenerator_instance_3_VAL runnableModels_Driver.RandomGenerator_instance_3
#define RandomGenerator_instance_3_REF &(runnableModels_Driver.RandomGenerator_instance_3)
#define RandomGenerator_instance_4_VAL runnableModels_Driver.RandomGenerator_instance_4
#define RandomGenerator_instance_4_REF &(runnableModels_Driver.RandomGenerator_instance_4)
#define deflate_fr_VAL runnableModels_Driver_CAL_MEM.deflate_fr
#define deflate_fl_VAL runnableModels_Driver_CAL_MEM.deflate_fl
#define deflate_vrl_VAL runnableModels_Driver_CAL_MEM.deflate_vrl
#define deflate_vrr_VAL runnableModels_Driver_CAL_MEM.deflate_vrr
#define ErrorModule_instance_VAL runnableModels_Driver.ErrorModule_instance
#define ErrorModule_instance_REF &(runnableModels_Driver.ErrorModule_instance)
#define error_FR_VAL runnableModels_Driver_CAL_MEM.error_FR
#define ErrorModule_instance_2_VAL runnableModels_Driver.ErrorModule_instance_2
#define ErrorModule_instance_2_REF &(runnableModels_Driver.ErrorModule_instance_2)
#define error_FL_VAL runnableModels_Driver_CAL_MEM.error_FL
#define ErrorModule_instance_3_VAL runnableModels_Driver.ErrorModule_instance_3
#define ErrorModule_instance_3_REF &(runnableModels_Driver.ErrorModule_instance_3)
#define error_RL_VAL runnableModels_Driver_CAL_MEM.error_RL
#define ErrorModule_instance_4_VAL runnableModels_Driver.ErrorModule_instance_4
#define ErrorModule_instance_4_REF &(runnableModels_Driver.ErrorModule_instance_4)
#define error_RR_VAL runnableModels_Driver_CAL_MEM.error_RR
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _RUNNABLEMODELS_DRIVER_AUTOMATIC_H_ */
