/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    TireSimulation_PC.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for project L1 node: TireSimulation_PC
 *
 **/
#include "TireSimulation_PC.l1.h"
#include "TireSimulation_PC.init.h"
#include "programId_TireSimulation_PC.h"

/**
 * Class initialization 
 **/
void initClass_L1_TireSimulation_PC (L1_TireSimulation_PC_Class* _ASCET_class)
{
    _ASCET_class->components_Simulation_Automatic = initInstance_L1_components_Simulation_Automatic();
    _ASCET_class->components_Globals_Automatic = initInstance_L1_components_Globals_Automatic();
}

/**
 * L1 protocol functions 
 **/

static uint8 *_L1_getPid (ASDObject *self, uint8 *_ASCET_data)
{
    uint8 defineFlag = true;
    uint32 pid = UNIQUE_PROGRAM_ID;
    addScalar (_ASCET_data, (uint8 *)&pid, sizeof(uint32));
    addScalar (_ASCET_data, (uint8 *)&defineFlag, sizeof(defineFlag));
    return (_ASCET_data);
}

static uint8 *_L1_getNVid(ASDObject *self, uint8 *_ASCET_data)
{
    uint8 defineFlag = true;
    uint32 nvid = 0;
    addScalar (_ASCET_data, (uint8 *)&nvid, sizeof(nvid));
    addScalar (_ASCET_data, (uint8 *)&defineFlag, sizeof(defineFlag));
    return (_ASCET_data);
}

static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    _L1_getPid,
    _L1_getNVid
};

/**
 * Global objects 
 **/
struct L1_TireSimulation_PC_Obj* L1_TireSimulation_PCInstance = NULL;

static ASDClassHeader L1_TireSimulation_PC_ClassHeader = {
	0, 2, 0, 2, &_ObjectMethodList, &_ClassMethodList
};

L1_TireSimulation_PC_Class L1_TireSimulation_PC_ClassObj = {{1, {&L1_TireSimulation_PC_ClassHeader}, {0}}};

bool initialized_TireSimulation_PC = false;

/**
 * Initialize this L1 component 
 **/
struct L1_TireSimulation_PC_Obj* initInstance_L1_TireSimulation_PC(void)
{
    struct L1_TireSimulation_PC_Obj* L1_Instance = NULL;
    if (!initialized_TireSimulation_PC) {
        /* for first time also static class data shall be initialized */
        initialized_TireSimulation_PC = true;
        initClass_L1_TireSimulation_PC(&L1_TireSimulation_PC_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_TireSimulation_PC);
    L1_TireSimulation_PCInstance = L1_Instance;

    return L1_Instance;
}
