#ifndef _ASD_ASCETTIRESIMUNITTEST_AUTOMATIC_H_
#define _ASD_ASCETTIRESIMUNITTEST_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    AscetTireSimUnitTest_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 11:21:38
*
* @brief   "AscetTireSimUnitTest>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "assertLib_Assert_Impl.h"
#include "components_Test_SOS_state_Automatic.h"
#include "components_Test_SOS_state_checkAllStates_Automatic.h"
#include "components_Test_SOS_state_checkAllStatesActive2_Automatic.h"
#include "components_Test_SOS_state_checkAllStatesDeactiv_Automatic.h"


/* component structure for project ASCETTIRESIMUNITTEST_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .............AscetTireSimUnitTest_Automatic */
#define _AscetTireSimUnitTest_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project AscetTireSimUnitTest_Automatic
 ******************************************************************************/



#endif /* _ASD_ASCETTIRESIMUNITTEST_AUTOMATIC_H_ */
