/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_TireDeviationTest_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:51:44
*
* @brief   "components_TireDeviationTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_TireDeviationTest_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_TireDeviationTest_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_TireDeviationTest'
 * data set:.....................................'COMPONENTS_TIREDEVIATIONTEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_TireDeviationTest_Automatic_RAM_SUBSTRUCT components_TireDeviationTest_RAM = {
   /* substruct: components_TireDeviationTest_RAM.td (modeled as:'td.components_TireDeviationTest') */
   {
      /* struct element:'components_TireDeviationTest_RAM.td.diff' (modeled as:'diff.td.components_TireDeviationTest') */
      0.0F,
      /* struct element:'components_TireDeviationTest_RAM.td.limit' (modeled as:'limit.td.components_TireDeviationTest') */
      0.0F,
      /* struct element:'components_TireDeviationTest_RAM.td.mean' (modeled as:'mean.td.components_TireDeviationTest') */
      0.0F,
      /* struct element:'components_TireDeviationTest_RAM.td.v' (modeled as:'v.td.components_TireDeviationTest') */
      0.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_TireDeviationTest_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_TireDeviationTest'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_TireDeviationTest'
 * data set:.....................................'COMPONENTS_TIREDEVIATIONTEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_TireDeviationTest_Automatic components_TireDeviationTest = {
   /* substruct: components_TireDeviationTest.td (modeled as:'td.components_TireDeviationTest') */
   {
      /* type descriptor pointer 'components_TireDeviation_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_TireDeviationTest_RAM.td
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_TireDeviationTest'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



