/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_ErrorModuleTest_noDeflation_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:51:44
*
* @brief   "components_ErrorModuleTest_noDeflation>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_ErrorModuleTest_noDeflation_Automatic.h"
#include "AscetTireSimUnitTest_Automatic.h"
#include "assertLib_Assert_Impl.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_ErrorModuleTest_noDeflation'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_ErrorModuleTest_noDeflation_Automatic_noDeflation'
 * ----------------------------------------------------------------------------
 * model name:...................................'noDeflation'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_ErrorModuleTest_noDeflation_Automatic_noDeflation (void)
{
   /* user defined local variables */
   float32 error;
   float32 same_v;
   float32 v;

   v = 10.0F;
   error = 0.5F;
   same_v = components_ErrorModule_Automatic_calc(false, v, error);
   ASSERT_NEAR((float64)same_v, (float64)v, 0.1);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_ErrorModuleTest_noDeflation_Automatic_noDeflation'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



