/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_TireDeviationTest_highDeviation_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:51:44
*
* @brief   "components_TireDeviationTest_highDeviation>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_TireDeviationTest_highDeviation_Automatic.h"
#include "AscetTireSimUnitTest_Automatic.h"
#include "assertLib_Assert_Impl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_TireDeviationTest_highDeviation_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_TireDeviationTest_highDeviation'
 * data set:.....................................'COMPONENTS_TIREDEVIATIONTEST_HIGHDEVIATION_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_TireDeviationTest_highDeviation_Automatic_RAM_SUBSTRUCT components_TireDeviationTest_highDeviation_RAM = {
   /* substruct: components_TireDeviationTest_highDeviation_RAM.td (modeled as:'td.components_TireDeviationTest_highDeviation') */
   {
      /* struct element:'components_TireDeviationTest_highDeviation_RAM.td.diff' (modeled as:'diff.td.components_TireDeviationTest_highDeviation') */
      0.0F,
      /* struct element:'components_TireDeviationTest_highDeviation_RAM.td.limit' (modeled as:'limit.td.components_TireDeviationTest_highDeviation') */
      0.0F,
      /* struct element:'components_TireDeviationTest_highDeviation_RAM.td.mean' (modeled as:'mean.td.components_TireDeviationTest_highDeviation') */
      0.0F,
      /* struct element:'components_TireDeviationTest_highDeviation_RAM.td.v' (modeled as:'v.td.components_TireDeviationTest_highDeviation') */
      0.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_TireDeviationTest_highDeviation_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_TireDeviationTest_highDeviation'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_TireDeviationTest_highDeviation'
 * data set:.....................................'COMPONENTS_TIREDEVIATIONTEST_HIGHDEVIATION_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_TireDeviationTest_highDeviation_Automatic components_TireDeviationTest_highDeviation = {
   /* substruct: components_TireDeviationTest_highDeviation.td (modeled as:'td.components_TireDeviationTest_highDeviation') */
   {
      /* type descriptor pointer 'components_TireDeviation_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_TireDeviationTest_highDeviation_RAM.td
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_TireDeviationTest_highDeviation'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_TireDeviationTest_highDeviation_Automatic_highDeviation'
 * ----------------------------------------------------------------------------
 * model name:...................................'highDeviation'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_TireDeviationTest_highDeviation_Automatic_highDeviation (void)
{
   /* user defined local variables */
   float32 limit;
   uint8 noFailure;
   float32 v;
   float32 v_mean;

   v = 100.06F;
   v_mean = 100.0F;
   limit = 0.05F;
   noFailure = false;
   ASSERT_TRUE(components_TireDeviation_Automatic_calc(&(components_TireDeviationTest_highDeviation.td), v, v_mean, limit, noFailure));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_TireDeviationTest_highDeviation_Automatic_highDeviation'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



