#ifndef _ASD_COMPONENTS_RINGBUFFERTEST_START_WITH_EMPTY_BUFFER_AUTOMATIC_H_
#define _ASD_COMPONENTS_RINGBUFFERTEST_START_WITH_EMPTY_BUFFER_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_RingBufferTest_start_with_empty_buffer_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:51:44
*
* @brief   "components_RingBufferTest_start_with_empty_buffer>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_RingBuffer_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_RingBufferTest_start_with_empty_buffer_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_RingBufferTest_start_with_empty_buffer_Automatic_RAM_SUBSTRUCT {
   struct components_RingBuffer_Automatic_RAM_SUBSTRUCT rb;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_RingBufferTest_start_with_empty_buffer_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_RingBufferTest_start_with_empty_buffer_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_RingBufferTest_start_with_empty_buffer_Automatic {
   struct components_RingBuffer_Automatic rb;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_RingBufferTest_start_with_empty_buffer_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: components_RingBufferTest_start_with_empty_buffer_Automatic */
#define _components_RingBufferTest_start_with_empty_buffer_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_RingBufferTest_start_with_empty_buffer_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_RingBufferTest_start_with_empty_buffer_Automatic_RAM_SUBSTRUCT components_RingBufferTest_start_with_empty_buffer_RAM;

/* forward declaration of component variable 'components_RingBufferTest_start_with_empty_buffer' */
/* containing 'ROM' memory class tree */
extern const struct components_RingBufferTest_start_with_empty_buffer_Automatic components_RingBufferTest_start_with_empty_buffer;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_RingBufferTest_start_with_empty_buffer_Automatic
 ******************************************************************************/
extern void components_RingBufferTest_start_with_empty_buffer_Automatic_start_with_empty_buffer (void);



#endif /* _ASD_COMPONENTS_RINGBUFFERTEST_START_WITH_EMPTY_BUFFER_AUTOMATIC_H_ */
