/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Test_SOS_state_checkAllStatesDeactiv_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:51:44
*
* @brief   "components_Test_SOS_state_checkAllStatesDeactiv>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Test_SOS_state_checkAllStatesDeactiv_Automatic.h"
#include "AscetTireSimUnitTest_Automatic.h"
#include "assertLib_Assert_Impl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Test_SOS_state_checkAllStatesDeactiv_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_Test_SOS_state_checkAllStatesDeactiv'
 * data set:.....................................'COMPONENTS_TEST_SOS_STATE_CHECKALLSTATESDEACTIV_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Test_SOS_state_checkAllStatesDeactiv_Automatic_RAM_SUBSTRUCT components_Test_SOS_state_checkAllStatesDeactiv_RAM = {
   /* struct element:'components_Test_SOS_state_checkAllStatesDeactiv_RAM.counter' (modeled as:'counter.components_Test_SOS_state_checkAllStatesDeactiv') */
   0,
   /* substruct: components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos (modeled as:'sos.components_Test_SOS_state_checkAllStatesDeactiv') */
   {
      /* struct element:'components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos.duration' (modeled as:'duration.sos.components_Test_SOS_state_checkAllStatesDeactiv') */
      0.0F,
      /* struct element:'components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos.myDT' (modeled as:'myDT.sos.components_Test_SOS_state_checkAllStatesDeactiv') */
      0.0F,
      /* struct element:'components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos.run' (modeled as:'run.sos.components_Test_SOS_state_checkAllStatesDeactiv') */
      0,
      /* struct element:'components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos.statelocation' (modeled as:'statelocation.sos.components_Test_SOS_state_checkAllStatesDeactiv') */
      0.0F,
      /* struct element:'components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos.status' (modeled as:'status.sos.components_Test_SOS_state_checkAllStatesDeactiv') */
      0,
      /* struct element:'components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos.x' (modeled as:'x.sos.components_Test_SOS_state_checkAllStatesDeactiv') */
      0,
      /* struct element:'components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos.y' (modeled as:'y.sos.components_Test_SOS_state_checkAllStatesDeactiv') */
      0,
      /* struct element:'components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos.aktiv' (modeled as:'aktiv.sos.components_Test_SOS_state_checkAllStatesDeactiv') */
      false,
      /* struct element:'components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos.sm' (modeled as:'sm.sos.components_Test_SOS_state_checkAllStatesDeactiv') */
      0U
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Test_SOS_state_checkAllStatesDeactiv_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_Test_SOS_state_checkAllStatesDeactiv'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_Test_SOS_state_checkAllStatesDeactiv'
 * data set:.....................................'COMPONENTS_TEST_SOS_STATE_CHECKALLSTATESDEACTIV_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_Test_SOS_state_checkAllStatesDeactiv_Automatic components_Test_SOS_state_checkAllStatesDeactiv = {
   /* substruct: components_Test_SOS_state_checkAllStatesDeactiv.sos (modeled as:'sos.components_Test_SOS_state_checkAllStatesDeactiv') */
   {
      /* type descriptor pointer 'components_SOS_state_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_Test_SOS_state_checkAllStatesDeactiv'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Test_SOS_state_checkAllStatesDeactiv_Automatic_checkAllStatesDeactiv'
 * ----------------------------------------------------------------------------
 * model name:...................................'checkAllStatesDeactiv'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_Test_SOS_state_checkAllStatesDeactiv_Automatic_checkAllStatesDeactiv (void)
{
   components_Test_SOS_state_checkAllStatesDeactiv_RAM.counter = 0;
   components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos.myDT = 0.1F;
   components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos.aktiv = false;
   while (components_Test_SOS_state_checkAllStatesDeactiv_RAM.counter < 30)
   {
      components_SOS_state_Automatic_sOS_stateStatemachineTrigger(&(components_Test_SOS_state_checkAllStatesDeactiv.sos));
      components_Test_SOS_state_checkAllStatesDeactiv_RAM.counter
         = ((components_Test_SOS_state_checkAllStatesDeactiv_RAM.counter <= 2147483646L) ? (components_Test_SOS_state_checkAllStatesDeactiv_RAM.counter + 1) : 2147483647L);
   } /* end while */
   ASSERT_NEAR((float64)components_Test_SOS_state_checkAllStatesDeactiv_RAM.sos.statelocation, 0.0, 0.1);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Test_SOS_state_checkAllStatesDeactiv_Automatic_checkAllStatesDeactiv'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



