#ifndef _ASD_COMPONENTS_TEST_SOS_STATE_CHECKALLSTATESDEACTIV_AUTOMATIC_H_
#define _ASD_COMPONENTS_TEST_SOS_STATE_CHECKALLSTATESDEACTIV_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Test_SOS_state_checkAllStatesDeactiv_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:51:44
*
* @brief   "components_Test_SOS_state_checkAllStatesDeactiv>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_SOS_state_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Test_SOS_state_checkAllStatesDeactiv_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_Test_SOS_state_checkAllStatesDeactiv_Automatic_RAM_SUBSTRUCT {
   sint32 counter;
   struct components_SOS_state_Automatic_RAM_SUBSTRUCT sos;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Test_SOS_state_checkAllStatesDeactiv_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_Test_SOS_state_checkAllStatesDeactiv_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_Test_SOS_state_checkAllStatesDeactiv_Automatic {
   struct components_SOS_state_Automatic sos;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_Test_SOS_state_checkAllStatesDeactiv_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: components_Test_SOS_state_checkAllStatesDeactiv_Automatic */
#define _components_Test_SOS_state_checkAllStatesDeactiv_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_Test_SOS_state_checkAllStatesDeactiv_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_Test_SOS_state_checkAllStatesDeactiv_Automatic_RAM_SUBSTRUCT components_Test_SOS_state_checkAllStatesDeactiv_RAM;

/* forward declaration of component variable 'components_Test_SOS_state_checkAllStatesDeactiv' */
/* containing 'ROM' memory class tree */
extern const struct components_Test_SOS_state_checkAllStatesDeactiv_Automatic components_Test_SOS_state_checkAllStatesDeactiv;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_Test_SOS_state_checkAllStatesDeactiv_Automatic
 ******************************************************************************/
extern void components_Test_SOS_state_checkAllStatesDeactiv_Automatic_checkAllStatesDeactiv (void);



#endif /* _ASD_COMPONENTS_TEST_SOS_STATE_CHECKALLSTATESDEACTIV_AUTOMATIC_H_ */
