/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Test_SOS_state_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:51:44
*
* @brief   "components_Test_SOS_state>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Test_SOS_state_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Test_SOS_state_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_Test_SOS_state'
 * data set:.....................................'COMPONENTS_TEST_SOS_STATE_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Test_SOS_state_Automatic_RAM_SUBSTRUCT components_Test_SOS_state_RAM = {
   /* struct element:'components_Test_SOS_state_RAM.counter' (modeled as:'counter.components_Test_SOS_state') */
   0,
   /* substruct: components_Test_SOS_state_RAM.sos (modeled as:'sos.components_Test_SOS_state') */
   {
      /* struct element:'components_Test_SOS_state_RAM.sos.duration' (modeled as:'duration.sos.components_Test_SOS_state') */
      0.0F,
      /* struct element:'components_Test_SOS_state_RAM.sos.myDT' (modeled as:'myDT.sos.components_Test_SOS_state') */
      0.0F,
      /* struct element:'components_Test_SOS_state_RAM.sos.run' (modeled as:'run.sos.components_Test_SOS_state') */
      0,
      /* struct element:'components_Test_SOS_state_RAM.sos.statelocation' (modeled as:'statelocation.sos.components_Test_SOS_state') */
      0.0F,
      /* struct element:'components_Test_SOS_state_RAM.sos.status' (modeled as:'status.sos.components_Test_SOS_state') */
      0,
      /* struct element:'components_Test_SOS_state_RAM.sos.x' (modeled as:'x.sos.components_Test_SOS_state') */
      0,
      /* struct element:'components_Test_SOS_state_RAM.sos.y' (modeled as:'y.sos.components_Test_SOS_state') */
      0,
      /* struct element:'components_Test_SOS_state_RAM.sos.aktiv' (modeled as:'aktiv.sos.components_Test_SOS_state') */
      false,
      /* struct element:'components_Test_SOS_state_RAM.sos.sm' (modeled as:'sm.sos.components_Test_SOS_state') */
      0U
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Test_SOS_state_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_Test_SOS_state'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_Test_SOS_state'
 * data set:.....................................'COMPONENTS_TEST_SOS_STATE_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_Test_SOS_state_Automatic components_Test_SOS_state = {
   /* substruct: components_Test_SOS_state.sos (modeled as:'sos.components_Test_SOS_state') */
   {
      /* type descriptor pointer 'components_SOS_state_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Test_SOS_state_RAM.sos
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_Test_SOS_state'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



