#ifndef _ASD_COMPONENTS_MODELTEST_AUTOMATIC_H_
#define _ASD_COMPONENTS_MODELTEST_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_ModelTest_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:51:44
*
* @brief   "components_ModelTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_Model_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_ModelTest_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_ModelTest_Automatic_RAM_SUBSTRUCT {
   float32 myDT;
   float32 vfl;
   float32 vfr;
   float32 vrl;
   float32 vrr;
   struct components_Model_Automatic_RAM_SUBSTRUCT m;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_ModelTest_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_ModelTest_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_ModelTest_Automatic {
   struct components_Model_Automatic m;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_ModelTest_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .............components_ModelTest_Automatic */
#define _components_ModelTest_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_ModelTest_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_ModelTest_Automatic_RAM_SUBSTRUCT components_ModelTest_RAM;

/* forward declaration of component variable 'components_ModelTest' */
/* containing 'ROM' memory class tree */
extern const struct components_ModelTest_Automatic components_ModelTest;


#endif /* _ASD_COMPONENTS_MODELTEST_AUTOMATIC_H_ */
