#ifndef _ASD_COMPONENTS_TIREDEVIATIONTEST_LOWDEVIATIONWHILECALIBRATION_AUTOMATIC_H_
#define _ASD_COMPONENTS_TIREDEVIATIONTEST_LOWDEVIATIONWHILECALIBRATION_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_TireDeviationTest_lowDeviationWhileCalibration_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:51:44
*
* @brief   "components_TireDeviationTest_lowDeviationWhileCalibration>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_TireDeviation_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_TireDeviationTest_lowDeviationWhileCalibration_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_TireDeviationTest_lowDeviationWhileCalibration_Automatic_RAM_SUBSTRUCT {
   struct components_TireDeviation_Automatic_RAM_SUBSTRUCT td;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_TireDeviationTest_lowDeviationWhileCalibration_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_TireDeviationTest_lowDeviationWhileCalibration_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_TireDeviationTest_lowDeviationWhileCalibration_Automatic {
   struct components_TireDeviation_Automatic td;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_TireDeviationTest_lowDeviationWhileCalibration_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: components_TireDeviationTest_lowDeviationWhileCalibration_Automatic */
#define _components_TireDeviationTest_lowDeviationWhileCalibration_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_TireDeviationTest_lowDeviationWhileCalibration_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_TireDeviationTest_lowDeviationWhileCalibration_Automatic_RAM_SUBSTRUCT components_TireDeviationTest_lowDeviationWhileCalibration_RAM;

/* forward declaration of component variable 'components_TireDeviationTest_lowDeviationWhileCalibration' */
/* containing 'ROM' memory class tree */
extern const struct components_TireDeviationTest_lowDeviationWhileCalibration_Automatic components_TireDeviationTest_lowDeviationWhileCalibration;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_TireDeviationTest_lowDeviationWhileCalibration_Automatic
 ******************************************************************************/
extern void components_TireDeviationTest_lowDeviationWhileCalibration_Automatic_lowDeviationWhileCalibration (void);



#endif /* _ASD_COMPONENTS_TIREDEVIATIONTEST_LOWDEVIATIONWHILECALIBRATION_AUTOMATIC_H_ */
