#ifndef _ASD_COMPONENTS_TIREMEANTEST_AUTOMATIC_H_
#define _ASD_COMPONENTS_TIREMEANTEST_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_TireMeanTest_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 09:51:44
*
* @brief   "components_TireMeanTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_TireMean_Automatic.h"


/* component structure for module COMPONENTS_TIREMEANTEST_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..........components_TireMeanTest_Automatic */
#define _components_TireMeanTest_Automatic_TYPE_DEF_





#endif /* _ASD_COMPONENTS_TIREMEANTEST_AUTOMATIC_H_ */
