/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    AscetTireSimApp.init.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Model initialization for application: AscetTireSimApp
 *
 **/
#pragma once

#include "a_basdef.h"
#include "protocol\l1\p_sysdef.h"

/**
 * initialize L1 Instance Tree 
 **/

/* Definition of the class structure */
typedef struct
{
    ASDObjectHeader objectHeader;
    struct L1_AscetTireSimApp_Obj* ASCET_TOP_Ptr;
} ROOT_AscetTireSimApp_Class;

/* Definition of the class instance structure */
struct ROOT_AscetTireSimApp_Obj
{
    ASDObjectHeader objectHeader;
};

extern ASDObject *initializeRoot_AscetTireSimApp(void);

/**
 * initialize model 
 **/
extern ASDObject *initializeModel (void);
