#ifndef _STRUCTURE_ASD_L1_AscetTireSimApp
#define _STRUCTURE_ASD_L1_AscetTireSimApp
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    AscetTireSimApp.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: AscetTireSimApp
 *
 **/
#include "a_basdef.h"
#include "runnableModels_sim_statemachine_Automatic.l1.h"
#include "interfaces_interfaces_Automatic.l1.h"
#include "components_Globals_Automatic.l1.h"
#include "runnableModels_Simulation_Automatic.l1.h"
#include "runnableModels_Driver_Automatic.l1.h"
#include "runnableModels_TirePressureMonitoring_Automatic.l1.h"
#include "runnableModels_ResetFunctionality_Automatic.l1.h"

/**
 * local variables object structure 
 **/
struct L1_AscetTireSimApp_Obj {
	ASDObjectHeader objectHeader;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
	struct L1_runnableModels_sim_statemachine_Automatic_Obj* runnableModels_sim_statemachine_Automatic;
	struct L1_interfaces_interfaces_Automatic_Obj* interfaces_interfaces_Automatic;
	struct L1_components_Globals_Automatic_Obj* components_Globals_Automatic;
	struct L1_runnableModels_Simulation_Automatic_Obj* runnableModels_Simulation_Automatic;
	struct L1_runnableModels_Driver_Automatic_Obj* runnableModels_Driver_Automatic;
	struct L1_runnableModels_TirePressureMonitoring_Automatic_Obj* runnableModels_TirePressureMonitoring_Automatic;
	struct L1_runnableModels_ResetFunctionality_Automatic_Obj* runnableModels_ResetFunctionality_Automatic;
} L1_AscetTireSimApp_Class;

extern L1_AscetTireSimApp_Class L1_AscetTireSimApp_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_AscetTireSimApp (L1_AscetTireSimApp_Class* _ASCET_class);
extern struct L1_AscetTireSimApp_Obj* initInstance_L1_AscetTireSimApp(void);
#endif /* _STRUCTURE_ASD_L1_AscetTireSimApp */
