/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    AscetTireSimApp.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for project L1 node: AscetTireSimApp
 *
 **/
#include "AscetTireSimApp.l1.h"
#include "AscetTireSimApp.init.h"
#include "programId_AscetTireSimApp.h"

/**
 * Class initialization 
 **/
void initClass_L1_AscetTireSimApp (L1_AscetTireSimApp_Class* _ASCET_class)
{
    _ASCET_class->components_sim_statemachine_Automatic = initInstance_L1_components_sim_statemachine_Automatic();
    _ASCET_class->interfaces_interfaces_Automatic = initInstance_L1_interfaces_interfaces_Automatic();
    _ASCET_class->components_Globals_Automatic = initInstance_L1_components_Globals_Automatic();
    _ASCET_class->components_Simulation_Automatic = initInstance_L1_components_Simulation_Automatic();
    _ASCET_class->components_Driver_Automatic = initInstance_L1_components_Driver_Automatic();
    _ASCET_class->components_TirePressureMonitoring_Automatic = initInstance_L1_components_TirePressureMonitoring_Automatic();
}

/**
 * L1 protocol functions 
 **/

static uint8 *_L1_getPid (ASDObject *self, uint8 *_ASCET_data)
{
    uint8 defineFlag = true;
    uint32 pid = UNIQUE_PROGRAM_ID;
    addScalar (_ASCET_data, (uint8 *)&pid, sizeof(uint32));
    addScalar (_ASCET_data, (uint8 *)&defineFlag, sizeof(defineFlag));
    return (_ASCET_data);
}

static uint8 *_L1_getNVid(ASDObject *self, uint8 *_ASCET_data)
{
    uint8 defineFlag = true;
    uint32 nvid = 0;
    addScalar (_ASCET_data, (uint8 *)&nvid, sizeof(nvid));
    addScalar (_ASCET_data, (uint8 *)&defineFlag, sizeof(defineFlag));
    return (_ASCET_data);
}

static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    _L1_getPid,
    _L1_getNVid
};

/**
 * Global objects 
 **/
struct L1_AscetTireSimApp_Obj* L1_AscetTireSimAppInstance = NULL;

static ASDClassHeader L1_AscetTireSimApp_ClassHeader = {
	0, 2, 0, 6, &_ObjectMethodList, &_ClassMethodList
};

L1_AscetTireSimApp_Class L1_AscetTireSimApp_ClassObj = {{1, {&L1_AscetTireSimApp_ClassHeader}, {0}}};

bool initialized_AscetTireSimApp = false;

/**
 * Initialize this L1 component 
 **/
struct L1_AscetTireSimApp_Obj* initInstance_L1_AscetTireSimApp(void)
{
    struct L1_AscetTireSimApp_Obj* L1_Instance = NULL;
    if (!initialized_AscetTireSimApp) {
        /* for first time also static class data shall be initialized */
        initialized_AscetTireSimApp = true;
        initClass_L1_AscetTireSimApp(&L1_AscetTireSimApp_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_AscetTireSimApp);
    L1_AscetTireSimAppInstance = L1_Instance;

    return L1_Instance;
}
