/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_SOS_state_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_SOS_state_Automatic
 *
 **/
#include "components_SOS_state_Automatic.l1.h"
#include "components_SOS_state_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_SOS_state_Automatic (L1_components_SOS_state_Automatic_Class* _ASCET_class)
{
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
static ASDClassHeader L1_components_SOS_state_Automatic_ClassHeader = {
	0, 0, 9, 0, &_ObjectMethodList, &_ClassMethodList
};

L1_components_SOS_state_Automatic_Class L1_components_SOS_state_Automatic_ClassObj = {{1, {&L1_components_SOS_state_Automatic_ClassHeader}, {0}}};

bool initialized_components_SOS_state_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_SOS_state_Automatic_Obj* initInstance_L1_components_SOS_state_Automatic(const struct components_SOS_state_Automatic* self)
{
    struct L1_components_SOS_state_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_SOS_state_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_SOS_state_Automatic = true;
        initClass_L1_components_SOS_state_Automatic(&L1_components_SOS_state_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_SOS_state_Automatic);
    L1_Instance->sm = initInstance_scalarWrapper((uint32)&sm_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->x = initInstance_scalarWrapper((uint32)&x_VAL, sizeof(sint32), ASD_VARIABLE);
    L1_Instance->status = initInstance_scalarWrapper((uint32)&status_VAL, sizeof(sint32), ASD_VARIABLE);
    L1_Instance->myDT = initInstance_scalarWrapper((uint32)&myDT_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->duration = initInstance_scalarWrapper((uint32)&duration_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->y = initInstance_scalarWrapper((uint32)&y_VAL, sizeof(sint32), ASD_VARIABLE);
    L1_Instance->run = initInstance_scalarWrapper((uint32)&run_VAL, sizeof(sint32), ASD_VARIABLE);
    L1_Instance->aktiv = initInstance_scalarWrapper((uint32)&aktiv_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->statelocation = initInstance_scalarWrapper((uint32)&statelocation_VAL, sizeof(float32), ASD_VARIABLE);

    return L1_Instance;
}
