/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_Simulation_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_Simulation_Automatic
 *
 **/
#include "components_Simulation_Automatic.l1.h"
#include "components_Simulation_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_Simulation_Automatic (L1_components_Simulation_Automatic_Class* _ASCET_class)
{
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
struct L1_components_Simulation_Automatic_Obj* L1_components_Simulation_AutomaticInstance = NULL;

static ASDClassHeader L1_components_Simulation_Automatic_ClassHeader = {
	0, 0, 24, 0, &_ObjectMethodList, &_ClassMethodList
};

L1_components_Simulation_Automatic_Class L1_components_Simulation_Automatic_ClassObj = {{1, {&L1_components_Simulation_Automatic_ClassHeader}, {0}}};

bool initialized_components_Simulation_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_Simulation_Automatic_Obj* initInstance_L1_components_Simulation_Automatic(void)
{
    struct L1_components_Simulation_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_Simulation_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_Simulation_Automatic = true;
        initClass_L1_components_Simulation_Automatic(&L1_components_Simulation_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_Simulation_Automatic);
    L1_Instance->Model_instance = initInstance_L1_components_Model_Automatic(&Model_instance_VAL);
    L1_Instance->TireDeviation_instance = initInstance_L1_components_TireDeviation_Automatic(&TireDeviation_instance_VAL);
    L1_Instance->RandomGenerator_instance = initInstance_L1_components_RandomGenerator_Automatic(&RandomGenerator_instance_VAL);
    L1_Instance->sfl = initInstance_scalarWrapper((uint32)&sfl_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->srl = initInstance_scalarWrapper((uint32)&srl_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->srr = initInstance_scalarWrapper((uint32)&srr_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->sfr = initInstance_scalarWrapper((uint32)&sfr_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->rand = initInstance_scalarWrapper((uint32)&rand_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->status_tire = initInstance_scalarWrapper((uint32)&status_tire_VAL, sizeof(uint8), ASD_PARAMETER);
    L1_Instance->diff_sfl = initInstance_scalarWrapper((uint32)&diff_sfl_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->diff_sfr = initInstance_scalarWrapper((uint32)&diff_sfr_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->diff_srr = initInstance_scalarWrapper((uint32)&diff_srr_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->diff_srl = initInstance_scalarWrapper((uint32)&diff_srl_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->mean = initInstance_scalarWrapper((uint32)&mean_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->fl_failure = initInstance_scalarWrapper((uint32)&fl_failure_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->fr_failure = initInstance_scalarWrapper((uint32)&fr_failure_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->rl_failure = initInstance_scalarWrapper((uint32)&rl_failure_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->rr_failure = initInstance_scalarWrapper((uint32)&rr_failure_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->base_v = initInstance_scalarWrapper((uint32)&base_v_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->base_noiselevel = initInstance_scalarWrapper((uint32)&base_noiselevel_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->vfr = initInstance_scalarWrapper((uint32)&vfr_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->vrr = initInstance_scalarWrapper((uint32)&vrr_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->vfl = initInstance_scalarWrapper((uint32)&vfl_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->vrl = initInstance_scalarWrapper((uint32)&vrl_VAL, sizeof(float32), ASD_VARIABLE);
    L1_components_Simulation_AutomaticInstance = L1_Instance;

    return L1_Instance;
}
