#ifndef _STRUCTURE_ASD_L1_runnableModels_ResetFunctionality_Automatic
#define _STRUCTURE_ASD_L1_runnableModels_ResetFunctionality_Automatic
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    runnableModels_ResetFunctionality_Automatic.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: runnableModels_ResetFunctionality_Automatic
 *
 **/
#include "a_basdef.h"
#include "runnableModels_ResetFunctionality_Automatic.h"
#include "runnableModels_ResetStateMachine_Automatic.l1.h"

/**
 * local variables object structure 
 **/
struct L1_runnableModels_ResetFunctionality_Automatic_Obj {
	ASDObjectHeader objectHeader;
	struct L1_runnableModels_ResetStateMachine_Automatic_Obj* ResetStateMachine_instance;
	struct L1_runnableModels_ResetStateMachine_Automatic_Obj* ResetStateMachine_instance_2;
	struct L1_runnableModels_ResetStateMachine_Automatic_Obj* ResetStateMachine_instance_3;
	struct L1_runnableModels_ResetStateMachine_Automatic_Obj* ResetStateMachine_instance_4;
	scalarWrapper_Obj* ResetButton;
	scalarWrapper_Obj* restValid;
	scalarWrapper_Obj* exitState;
	scalarWrapper_Obj* test;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
} L1_runnableModels_ResetFunctionality_Automatic_Class;

extern L1_runnableModels_ResetFunctionality_Automatic_Class L1_runnableModels_ResetFunctionality_Automatic_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_runnableModels_ResetFunctionality_Automatic (L1_runnableModels_ResetFunctionality_Automatic_Class* _ASCET_class);
extern struct L1_runnableModels_ResetFunctionality_Automatic_Obj* initInstance_L1_runnableModels_ResetFunctionality_Automatic(void);
#endif /* _STRUCTURE_ASD_L1_runnableModels_ResetFunctionality_Automatic */
