/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    runnableModels_sim_statemachine_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: runnableModels_sim_statemachine_Automatic
 *
 **/
#include "runnableModels_sim_statemachine_Automatic.l1.h"
#include "runnableModels_sim_statemachine_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_runnableModels_sim_statemachine_Automatic (L1_runnableModels_sim_statemachine_Automatic_Class* _ASCET_class)
{
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
struct L1_runnableModels_sim_statemachine_Automatic_Obj* L1_runnableModels_sim_statemachine_AutomaticInstance = NULL;

static ASDClassHeader L1_runnableModels_sim_statemachine_Automatic_ClassHeader = {
	0, 0, 2, 0, &_ObjectMethodList, &_ClassMethodList
};

L1_runnableModels_sim_statemachine_Automatic_Class L1_runnableModels_sim_statemachine_Automatic_ClassObj = {{1, {&L1_runnableModels_sim_statemachine_Automatic_ClassHeader}, {0}}};

bool initialized_runnableModels_sim_statemachine_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_runnableModels_sim_statemachine_Automatic_Obj* initInstance_L1_runnableModels_sim_statemachine_Automatic(void)
{
    struct L1_runnableModels_sim_statemachine_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_runnableModels_sim_statemachine_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_runnableModels_sim_statemachine_Automatic = true;
        initClass_L1_runnableModels_sim_statemachine_Automatic(&L1_runnableModels_sim_statemachine_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_runnableModels_sim_statemachine_Automatic);
    L1_Instance->SOS_state_instance = initInstance_L1_components_SOS_state_Automatic(&SOS_state_instance_VAL);
    L1_Instance->failure = initInstance_scalarWrapper((uint32)&failure_VAL, sizeof(uint8), ASD_PARAMETER);
    L1_runnableModels_sim_statemachine_AutomaticInstance = L1_Instance;

    return L1_Instance;
}
