#ifndef _COMPONENTS_SIMULATION_AUTOMATIC_H_
#define _COMPONENTS_SIMULATION_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Simulation_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Simulation
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define Model_instance_VAL components_Simulation.Model_instance
#define Model_instance_REF &(components_Simulation.Model_instance)
#define vfr_VAL components_Simulation_CAL_MEM.vfr
#define vfl_VAL components_Simulation_CAL_MEM.vfl
#define vrr_VAL components_Simulation_CAL_MEM.vrr
#define vrl_VAL components_Simulation_CAL_MEM.vrl
#define sfl_VAL components_Simulation_RAM.sfl
#define srl_VAL components_Simulation_RAM.srl
#define srr_VAL components_Simulation_RAM.srr
#define sfr_VAL components_Simulation_RAM.sfr
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_SIMULATION_AUTOMATIC_H_ */
