/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Model_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    10.03.2019 17:35:01
*
* @brief   "components_Model>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Model_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define sfl_VAL (self->components_Model_Automatic_RAM->sfl)
#define sfr_VAL (self->components_Model_Automatic_RAM->sfr)
#define srl_VAL (self->components_Model_Automatic_RAM->srl)
#define srr_VAL (self->components_Model_Automatic_RAM->srr)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Model_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_Model_Automatic_calc (
               const struct components_Model_Automatic * self,
   /* IN    */ const float32                             vfr,
   /* IN    */ const float32                             vrr,
   /* IN    */ const float32                             vfl,
   /* IN    */ const float32                             vrl,
   /* IN    */ const float32                             my_dT
   )
{
   sfl_VAL = sfl_VAL + (vfl * my_dT);
   sfr_VAL = sfr_VAL + (vfr * my_dT);
   srl_VAL = srl_VAL + (vrl * my_dT);
   srr_VAL = srr_VAL + (vrr * my_dT);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Model_Automatic_calc'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Model_Automatic_getSfl'
 * ----------------------------------------------------------------------------
 * model name:...................................'getSfl'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Model_Automatic_getSfl ( const struct components_Model_Automatic * self)
{
   return sfl_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Model_Automatic_getSfl'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Model_Automatic_getSfr'
 * ----------------------------------------------------------------------------
 * model name:...................................'getSfr'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Model_Automatic_getSfr ( const struct components_Model_Automatic * self)
{
   return sfr_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Model_Automatic_getSfr'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Model_Automatic_getSrl'
 * ----------------------------------------------------------------------------
 * model name:...................................'getSrl'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Model_Automatic_getSrl ( const struct components_Model_Automatic * self)
{
   return srl_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Model_Automatic_getSrl'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Model_Automatic_getSrr'
 * ----------------------------------------------------------------------------
 * model name:...................................'getSrr'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Model_Automatic_getSrr ( const struct components_Model_Automatic * self)
{
   return srr_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Model_Automatic_getSrr'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



