#ifndef _COMPONENTS_GLOBALS_AUTOMATIC_H_
#define _COMPONENTS_GLOBALS_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Globals_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Globals
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_GLOBALS_AUTOMATIC_H_ */
