#ifndef _ASD_COMPONENTS_MODEL_AUTOMATIC_H_
#define _ASD_COMPONENTS_MODEL_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Model_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    10.03.2019 17:35:01
*
* @brief   "components_Model>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_Model_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_Model_Automatic_RAM_SUBSTRUCT {
   float32 sfl;
   float32 sfr;
   float32 srl;
   float32 srr;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_Model_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_Model_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_Model_Automatic {
   struct components_Model_Automatic_RAM_SUBSTRUCT * components_Model_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_Model_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .................components_Model_Automatic */
#define _components_Model_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_Model_Automatic
 ******************************************************************************/
extern void components_Model_Automatic_calc (
               const struct components_Model_Automatic * self,
   /* IN    */ const float32                             vfr,
   /* IN    */ const float32                             vrr,
   /* IN    */ const float32                             vfl,
   /* IN    */ const float32                             vrl,
   /* IN    */ const float32                             my_dT
   );
extern float32 components_Model_Automatic_getSfl ( const struct components_Model_Automatic * self);
extern float32 components_Model_Automatic_getSfr ( const struct components_Model_Automatic * self);
extern float32 components_Model_Automatic_getSrl ( const struct components_Model_Automatic * self);
extern float32 components_Model_Automatic_getSrr ( const struct components_Model_Automatic * self);



#endif /* _ASD_COMPONENTS_MODEL_AUTOMATIC_H_ */
