#ifndef _ASD_COMPONENTS_GLOBALS_AUTOMATIC_H_
#define _ASD_COMPONENTS_GLOBALS_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Globals_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    10.03.2019 17:35:01
*
* @brief   "components_Globals>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module COMPONENTS_GLOBALS_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...............components_Globals_Automatic */
#define _components_Globals_Automatic_TYPE_DEF_





#endif /* _ASD_COMPONENTS_GLOBALS_AUTOMATIC_H_ */
