#ifndef _ASD_TIRESIMULATION_PC_AUTOMATIC_H_
#define _ASD_TIRESIMULATION_PC_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    TireSimulation_PC_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    10.03.2019 17:35:01
*
* @brief   "TireSimulation_PC>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_Globals_Automatic.h"
#include "components_Simulation_Automatic.h"


/* component structure for project TIRESIMULATION_PC_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ................TireSimulation_PC_Automatic */
#define _TireSimulation_PC_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project TireSimulation_PC_Automatic
 ******************************************************************************/



#endif /* _ASD_TIRESIMULATION_PC_AUTOMATIC_H_ */
